In [3]:
import numpy as np
arr = np.zeros((5, 5))
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
arr[0][0]=34
arr[0][1]=23
arr[0][2]=54
arr[0][3]=46
arr[0][4]=54
print(arr)

[[34. 23. 54. 46. 54.]
 [ 0. 34.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [12]:
import pandas as pd

data = {
    "Name": ["a", "b"],
    "Age": [21, 23]
}

df = pd.DataFrame(data)
print(df)


  Name  Age
0    a   21
1    b   23


In [2]:
#tuple concattion
t1=(1,2,3)
t2=(4,5,60)
print(t1+t2)

(1, 2, 3, 4, 5, 60)


In [5]:
#capitalize method in python
a="abhishek nisnishahad"#only starting word will be capital 
print(a.capitalize())

Abhishek nisnishahad


In [4]:
a="Abhishek nishad"
print(a.capitalize())

Abhishek nishad


In [6]:
a = "abhishek nishad"
print(a.title())


Abhishek Nishad


In [14]:
# insert the element in given list
lst = [1, 2, 3, 4]

# lst.insert(index, value)
# insert(1, 0) means:
# add 0 at index 1
# It does NOT replace any element, it only shifts elements to the right
lst.insert(1, 0)

print(lst)  # Output: [1, 0, 2, 3, 4]
lst.append(5)#add the list element at the end of the list
print(lst)
lst[0]=1
print(lst)


[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4, 5]
[1, 0, 2, 3, 4, 5]


In [15]:
lst = [1, 2, 2, 3, 4, 4, 5]

# set removes duplicates but does NOT keep original order
lst = list(set(lst))
print(lst)


[1, 2, 3, 4, 5]


In [17]:
#list comprehension
list=[i for i in range(10)]
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [19]:
even_odd = lambda n: "Even" if n % 2 == 0 else "Odd"

print(even_odd(10))   # Even
print(even_odd(7))    # Odd


Even
Odd


In [21]:
even_odd=lambda n : "Even" if n % 2 == 0 else "odd"
print(even_odd(10))

Even


In [28]:
#sort and sorted method
lst=[43,35,43,354]
lst.sort()
print(lst)

lst2=[43,35,43,354]
newlst=sorted(lst2)
print(newlst)


[35, 43, 43, 354]
[35, 43, 43, 354]


In [30]:
for i in range(len(lst)):
    print(lst[i])


123
34
343
3


In [31]:
lst = [123, 34, 343, 3]

for i in xrange(len(lst)):
    print(lst[i])


NameError: name 'xrange' is not defined

In [41]:
def sum_numbers(*nums):  # use *nums for multiple positional arguments
    total = 0
    for i in nums:
        total += i  # add each number to total
    print(total)

sum_numbers(1, 2, 3)  # Output: 6


6


In [42]:
def sum_numbers(*nums):
    total=0
    for i in nums:
        total=total + i
    print(total)
sum_numbers(2,4,50)

56


In [43]:
#generators
def my_gen():
    yield 10
    yield 20
    yield 30
g=my_gen()
print(next(g))
print(next(g))

10
20


<h2>Shallow copy</h2>

In [45]:
#shallow copy not nested list
lst=[1,2,3,4]
lst2=lst.copy()
print(lst)
print(lst2)# create new seprate list ,so chnaging simple values in the copied lsit does not affect the original list,if not nested list
lst2[1]=10
print(lst)
print(lst2)

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 10, 3, 4]


In [50]:
#shallow copy with nested loop->update are reflected on both list if anyone update the list
lst=[[1,2,3,4],[5,6,7,8]]
lst2=lst.copy()
print(lst2[1][0])
lst2[1][0]=1000
print(lst)
print(lst2)
lst.append([423,343,434])#append only the lst not lst2
print(lst)
print(lst2)


5
[[1, 2, 3, 4], [1000, 6, 7, 8]]
[[1, 2, 3, 4], [1000, 6, 7, 8]]
[[1, 2, 3, 4], [1000, 6, 7, 8], [423, 343, 434]]
[[1, 2, 3, 4], [1000, 6, 7, 8]]


<h2>Deep copy</h2>

In [52]:
#deep copy without nested loop->It behave like the shallow copy 
import copy
lst1=[1,2,3,4]
lst2=copy.deepcopy(lst1)
lst2[1]=100
print(lst1)
print(lst2)

[1, 2, 3, 4]
[1, 100, 3, 4]


In [54]:
#deep copy with nested loop
lst1=[[1,2,3],[4,5,6],[7,8,9]]
lst2=copy.deepcopy(lst1)
lst2[1][0]=100#update is not reflected to the main copy
print(lst2)
print(lst1)

[[1, 2, 3], [100, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


<h3>abstract</h3>

In [56]:
from abc import ABC, abstractmethod

class Vehicle(ABC):
    def fuel(self):
        print("Fuel is needed")
    
    @abstractmethod
    def speed(self):
        pass

class Bike(Vehicle):
    def speed(self):
        print("Bike speed is 80 km/h")

obj = Bike()
obj.fuel()   # Output: Fuel is needed
obj.speed()  # Output: Bike speed is 80 km/h


Fuel is needed
Bike speed is 80 km/h


In [5]:
print(bool(""))

False


In [6]:
a=[1,2,3,4]
b=a
b.append(5)
print(a)

[1, 2, 3, 4, 5]


In [7]:
c=0.3+0.2
print(c)

0.5


In [8]:
c=0.1+0.2
print(c)

0.30000000000000004


In [16]:
print(0.1+0.1==0.2)

True


In [17]:
print(0.2+0.4==0.6)

False


In [15]:
print(0.9+0.9==1.8)

True


In [18]:
f = lambda x: x + 1
print(type(f))


<class 'function'>


<h1>Fibbonacci Series using generator</h1>

In [23]:
def fib():
    a,b=0,1
    while True:
        yield a
        a,b=b,a+b

f=fib()
print(next(f))
print(next(f))
print(next(f))
print(next(f))


0
1
1
2


In [30]:
str='The sky is blue'
trim=str.split()
print(trim)
rev=trim[::-1]
print(rev)
rev_str=' '.join(rev)
print("After reverse the sentence:",rev_str)

['The', 'sky', 'is', 'blue']
['blue', 'is', 'sky', 'The']
After reverse the sentence: blue is sky The


In [32]:
#find the charter frequncy
str='abacaagadaff'
n=len(str)-1
frequency_map={}
for i in str:
    if i not in frequency_map:
        frequency_map[i]=1
    elif i in frequency_map:
        frequency_map[i]+=1
print(frequency_map)
        


{'a': 6, 'b': 1, 'c': 1, 'g': 1, 'd': 1, 'f': 2}


In [38]:
#find the maximum and minimu
arr=[23,24,43,5,45,1,4,34]
min=arr[0]
max=arr[0]
second_min=float('inf')

for i in arr:
    if i<=min:
        second_min=min
        min=i
    elif i<second_min and i !=min:
        second_min=i
    elif i>=max:
        max=i
   
print(max,min,second_min)

45 1 4


In [42]:
#raise exception
l=[1,2,3,4]
sum=0
for i in l:
    if i==13:
        raise Exception("Exception : 1 is found")
    else:
        sum=sum+i
print(sum)

10


In [54]:
def decorator(func):
    def wrapper(a,b):
        print("sum")
        return func(a,b)
    return wrapper
@decorator
def add(a,b):
    return a+b
print(add(1,2))

sum
3


In [1]:
print(bool("False"))

True


In [5]:
x=[]
y=x
y +=[1,2]
print(x)
print(y)

[1, 2]
[1, 2]


In [4]:
x=[1,2,3]
y=x[:]
y.append(4)
print(x)
print(y)

[1, 2, 3]
[1, 2, 3, 4]


In [6]:
print([] == [])

True


In [7]:
print([] is [])

False


In [9]:
a=10
print(a)
a=20
print(a)

10
20


In [10]:
a=10 
def func():
    a=20
    print(a)
func()
print(a)


20
10


In [11]:
a=10
def func():
    global a
    a=20
    print(a)
func()
print(a)

20
20


In [12]:
print(0.1+0.2==0.3)

False


In [13]:
print(type(lambda x:x))

<class 'function'>


In [19]:
x=None
print(x)
print(x == False)
print(x is False)

None
False
False


In [23]:
print(bool([" "]),bool({}),bool(()))

True False False


In [24]:
a=[1,2,3]
print(a * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [25]:
print("5" *3)

555


In [28]:
def add(x,y=[]):
    y.append(x)
    return y
print(add(1))
print(add(3))

[1]
[1, 3]


In [30]:
x=(1,2,[3,4])
x[2].append(5)
print(x)

(1, 2, [3, 4, 5])


In [33]:
print(type(int))

<class 'type'>


In [36]:
a=20
print(type(type(type(a))))

<class 'type'>


In [40]:
print(bool(''))

False


In [41]:
print(bool('0'))

True


In [44]:
a=[1,2,3]
print(a)
b=a
print(b)
a=a+[4]
print(b)
print(a)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3, 4]


In [45]:
a=[1,2,3]
b=a
print(b,a)
a +=[4]
print(a)
print(b)

[1, 2, 3] [1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4]


In [49]:
print(True ==0)
print(False ==1)
print(True is 1)

False
False
False


In [51]:
print(True ==1)
print(False ==0)
print(True is 0)

True
True
False


In [52]:
print(type(None))

<class 'NoneType'>


In [56]:
x=5
def test():
    
    print(x)
test()

5


In [61]:
x=5 
def test():
    global x
    x= x + 1
    print(x)
test()

6


In [62]:
x=5 
def test():
    
    x= x + 1
    print(x)
test()

UnboundLocalError: cannot access local variable 'x' where it is not associated with a value

In [63]:
print('abhi'[::-1])

ihba


In [65]:
print({} == {})
print({} is {})

True
False


In [74]:
print( 5 and 0)#0->False, 1->True
print(0 and 5)
print(5 or 0)#5 is none zero element or not emepty so  5 will be return
print(0 or 5)
#or dondo value check karega dono me se koi ek true raha to o return karega 

0
0
5
5


In [73]:
print(1 and True)
print(1 and 1)
print(1 and 2)
print(1 and 0)

True
1
2
0


In [79]:
print(0 and 0)
print(0 and False)
print(0 and True)
print(1 and 0)
#0->False : 0 false ko batata hai, aur yanha pahal value hi false hai to 'and' False return kar dega

0
0
0
0


In [95]:
print( not not bool(['ab']))

True


In [96]:
print( not not bool([]))

False


In [99]:
print(tuple([12,32]))

(12, 32)


In [103]:
x=12
y=12
print(id(x))
print(id(y))
print(x is y)
print(x == y)

140735935591688
140735935591688
True
True


In [104]:
x=[12]
y=[12]
print(id(x))
print(id(y))
print(x is y)
print(x == y)

2386335162176
2386334886080
False
True


In [105]:
print([i for i in range(3)])

[0, 1, 2]


In [108]:
a=[[],[],[]] 
print(a)
a[0].append(1)
print(a)

[[], [], []]
[[1], [], []]


In [109]:
a=[[]] * 3 
print(a)
a[0].append(1)
print(a)

[[], [], []]
[[1], [1], [1]]


In [110]:
print(type({1}))

<class 'set'>


In [111]:
print(type({}))

<class 'dict'>


In [112]:
x=[1,2,3]
print(x.pop())
print(x)

3
[1, 2]


In [117]:
print(sum([True,True, True, False,False,False,5]))#True-1, False->0

8


In [118]:
print(sum([1,1,1,0,0,0,5]))

8


In [119]:
print(all([1,0,3]))

False


In [122]:
print(all([1,1,1]))#all() returns True only if ALL elements are True

True


In [125]:
print(len("  "))

2


In [129]:
join=" ".join(['My', 'name', 'is','Abhishek','Nishad'])
print(join)

My name is Abhishek Nishad


In [137]:
str='I love my india'
s=str.split()
print(s)
rev=s[::-1]
print(rev)
rev_str=" ".join(rev)
print(rev_str)

['I', 'love', 'my', 'india']
['india', 'my', 'love', 'I']
india my love I


In [138]:
a='hello'
b=''.join(['hel','lo'])
print(a==b)
print(a is b)

True
False


In [151]:
d={1.0:"ab",1:"B",2.4:"c"}
print(d[1])

B


In [149]:
x=10
def func():
    print(x)
    x=5
    print(x)
func()

UnboundLocalError: cannot access local variable 'x' where it is not associated with a value

In [150]:
result=True + True + True + False - True
print(result)

2


In [167]:
my_dic={1:'Apple',True:'Banana',1.0:"mango"}#True=1 , this is overwrite with 1.0
print(my_dic[1.0])
print(my_dic[1])
print(len(my_dic))
print(my_dic.items())
print(my_dic.keys())
print(my_dic.values())

mango
mango
1
dict_items([(1, 'mango')])
dict_keys([1])
dict_values(['mango'])


In [171]:
my_dic={1:'Apple',False:'Banana',1.0:"mango"}# 1 and True=1 , this is overwrite with 1.0, 1.0 will be converted into 1
print(my_dic[1.0])
print(my_dic[1])
print(len(my_dic))
print(my_dic.items())
print(my_dic.keys())
print(my_dic.values())

mango
mango
2
dict_items([(1, 'mango'), (False, 'Banana')])
dict_keys([1, False])
dict_values(['mango', 'Banana'])


In [175]:
s=""
for i in range(100):
    s +=str(i)#string is immutable
print(s)
    

TypeError: 'str' object is not callable

In [177]:
s = ""
for i in range(100):
    s += str(i)   # now s keeps updating
print(s)


TypeError: 'str' object is not callable

In [178]:
my_string = ""
for i in range(100):
    my_string += str(i)   # now str() works
print(my_string)


TypeError: 'str' object is not callable

In [179]:
result=[] or 'Python' or 0 or True #python is true so condition will not check further
print(result)

Python


In [181]:
result= True or [] or 'Python' or 0 or True #First condtion is True
print(result)

True


In [183]:

lst=[ i for i in range(1,11)]
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [188]:
d={"a":1,"b":3,3:'c'}# if key is not found then del give error, but pop method see value which set by us, if key not found 
del d["a"]
d.pop(5,"not fount")


'not fount'

In [189]:
print(round(2.5))
print(round(4.5))

2
4


In [192]:
t1=(1,2)
print(t1)
id1=id(t1)
t1 +=(3,)
print(t1)
id2=id(t1)
print(id1 == id2)

(1, 2)
(1, 2, 3)
False


In [198]:
t1 = (1, 2)
temp = list(t1)
temp.insert(1, 3)   # insert 3 at index 1
t1 = tuple(temp)
print(t1)


(1, 3, 2)


In [208]:
lst=[34,35,35,542,2,1]
lst.sort()
print(lst)
print(lst.sort())
'''
print(lst.sort())

Here, you are printing the return value of lst.sort().

Since sort() does not return anything, it returns None.

'''

[1, 2, 34, 35, 35, 542]
None


In [211]:
lst=[34,35,35,542,2,1]
print(sorted(lst))#It does not change the original list
print(lst)
sorted_list=sorted(lst)
print(sorted_list)

[1, 2, 34, 35, 35, 542]
[34, 35, 35, 542, 2, 1]
[1, 2, 34, 35, 35, 542]


In [213]:
print(all([]))
print(any([]))

True
False


In [215]:
print(all([True,False]))
print(any([False,True]))

False
True


write a python funciton that will reverse a string without using slicing operation or reverse() function.
write a program to delete all constant from a given string. 'Python and Data Science"



In [220]:
str='abc'
print(''.join(reversed(str)))

c b a


In [224]:
#write a program to delete all constant from a given string. 'Python and Data Science'
str='Python and Data Science'
vowel='aeiouAEIOU'
result=''
for i in str:
    if i not in vowel:
        result=result+i
print(result)

Pythn nd Dt Scnc


In [228]:
#write a program that wil find the sum of all the prime numbers between 1 and N
n=43

count=0
for i in range(1,n+1):
    if n%i==0:
        count=count+1
    else:
        continue
if count==2:
    print('prime')
else:
    print('not prime')

        

prime


In [ ]:
n=231
for i in range(2,n):
    if n%i==0:
        print('not prime')
        break
    else:
        print('prime')
        break
        

In [248]:
print("write a program that wil find the sum of all the prime numbers between 1 and N")
N = int(input("Enter N: "))

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, num):
        if num % i == 0:
            return False
    return True

total = 0
prime_number=[]
for i in range(2, N + 1):
    if is_prime(i):
        prime_number.append(i)
        total += i
print("Prime numbers:",prime_number)
print("Sum of prime numbers:", total)



write a program that wil find the sum of all the prime numbers between 1 and N


Enter N:  10


Prime numbers: [2, 3, 5, 7]
Sum of prime numbers: 17


In [1]:
lst=[1,2,3]
lst.extend([34,545,54])
lst.insert(0,0)
del lst[0]
print(lst)

[1, 2, 3, 34, 545, 54]


In [3]:
for i in range(5,1,-1):
    print(i)

5
4
3
2


In [6]:
print(5/2)
print(5//2)
print(-5/2)
print(-5//2)

2.5
2
-2.5
-3


In [8]:
print(10%3)
print(-10%3)

1
2


In [12]:
print(-23%7)

5


In [19]:
# Given expression
print(-23 % 7)          # Final output will be 5

# Step 1: Understand floor division
# -23 / 7 = -3.285...
# Floor means go to the smaller integer (left on number line)
-23 // 7                # = -4

# Step 2: Python modulus formula
# a % b = a - (a // b) * b

# Apply formula
# -23 % 7
# = -23 - (-4 * 7)
# = -23 + 28
# = 5

# Step 3: Verify logic
# Python ensures remainder has same sign as divisor (7 is positive)
# So remainder must be positive

# Final result
print(-23 % 7)          # 5


5
5


In [22]:
import math
print(math.floor(3/2))
print(math.ceil(3/2))
print(math.pow(2,2))

1
2
4.0


In [26]:
n=5
arr=[0]*n
print(arr)

[0, 0, 0, 0, 0]


In [27]:
a,b,c=[1,2,3]
print(a,b,c)

1 2 3


In [28]:
nums=[1,2,4]
for i, num in enumerate(nums):
    print(i,num)

0 1
1 2
2 4


In [34]:
arr=[34,3,54,4,634,43,54]
arr.sort()
print(arr)
arr.sort(reverse=True)
print(arr)

[3, 4, 34, 43, 54, 54, 634]
[634, 54, 54, 43, 34, 4, 3]


In [32]:
arr=[34,3,54,4,634,43,54]
s=sorted(arr)
print(s)

[3, 4, 34, 43, 54, 54, 634]


In [35]:
a,b=[1,2,3]
print(a,b)

ValueError: too many values to unpack (expected 2)

In [36]:
arr=['bob','alice','jane','doe']
arr.sort()#sort using Alphabetic
print(arr)

['alice', 'bob', 'doe', 'jane']


In [37]:
arr=['bob','alice','jane','doe']
arr.sort(key=lambda x: len(x))
print(arr)

['bob', 'doe', 'jane', 'alice']


In [39]:
arr=[i for i in range(1,22)]
print(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


In [40]:
arr=[i+i for i in range(2,5)]
print(arr)

[4, 6, 8]


In [41]:
arr=[[0] *4  for i in range(4)]
print(arr)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [44]:
s='abc'
print(s[0:2])
s[0]='A'
print(s)

ab


TypeError: 'str' object does not support item assignment

In [46]:
s='abc'
print(id(s))
print(s)
s=s+'def'
print(id(s))
print(s)

1530644888576
abc
1530759034080
abcdef


In [47]:
s='abc'
print(id(s))
print(s)
s +='def'#creates the new string
print(id(s))
print(s)

1530644888576
abc
1530759439312
abcdef


In [48]:
print(int('123') + int('1234'))

1357


In [49]:
print(str(123) +str(123))

123123


In [53]:
#find the ascii value
print(ord('a'))
print(ord('b'))
print(ord('c'))
print(ord('e'))

97
98
99
101


In [56]:
s=['a','b','c']
j=" ".join(s)
print(j)

a b c


In [61]:
nums='madam'
def palindrome(nums):
    f=0
    n=len(nums)-1
    l=n
    while f<=l:
        if nums[f] !=nums[l]:
            return False
        else:
            f=f+1
            l=l-1
    return True
palindrome(nums)
    
    

True

In [73]:
def fib(n):
    print("Series")
    a,b=0,1
    print(a)
    for i in range(n):
        sum=a+b
        print(sum)
        a=b
        b=sum
    print("Sum of the series:",sum)
fib(5)

Series
0
1
2
3
5
8
Sum of the series: 8


In [74]:
s = "aabbccdddeeee"

result = ""              # final compressed string
count = 1                # count of current character

for i in range(1, len(s)):
    if s[i] == s[i-1]:   # same character as previous
        count += 1       # increase count
    else:
        result += s[i-1] + str(count)  # store char + count
        count = 1        # reset count for new character

# add last character and its count
result += s[-1] + str(count)

print(result)


a2b2c2d3e4


In [79]:
def fizzbuzz(n):
    for i in range(1,n+1):
        if i%3==0 and i%5==0:
            print("Fizzbuzz")
        elif i%3 ==0:
            print('Fizz')
        elif i%5==0:
            print('Buzz')
        else:
            print(i)
fizzbuzz(10)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz


In [88]:
dic = {
    3: 'fizz',
    5: 'buzz'
}

for i in range(1, 10):
    result = ""                    # reset for each number

    for k, v in dic.items():
        if i % k == 0:             # divisible check
            result += v            # add fizz / buzz

    if not result:                 # if result is still empty
        result = i                # assign number

    print(result)                  # print for each i


1
2
fizz
4
buzz
fizz
7
8
fizz


In [90]:
#charter occerance
str='aabbccdd'
ch={}
for i in str:
    if i not in ch:
        ch[i]=1
        
    elif  i in ch:
        ch[i]=ch[i]+1
print(ch)

{'a': 2, 'b': 2, 'c': 2, 'd': 2}


In [105]:
str='This_Is_A_Good_Morning'
print("Original String:\n",str)
l=[]
split_str=str.split('_')

for i in split_str:
    l.append(i[0].lower() + i[1:].upper())
output_str=".".join(l)
print('Expected ouput\n',output_str)


Original String:
 This_Is_A_Good_Morning
Expected ouput
 tHIS.iS.a.gOOD.mORNING
