In [3]:
import numpy as np
arr = np.zeros((5, 5))
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
arr[0][0]=34
arr[0][1]=23
arr[0][2]=54
arr[0][3]=46
arr[0][4]=54
print(arr)

[[34. 23. 54. 46. 54.]
 [ 0. 34.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [12]:
import pandas as pd

data = {
    "Name": ["a", "b"],
    "Age": [21, 23]
}

df = pd.DataFrame(data)
print(df)


  Name  Age
0    a   21
1    b   23


In [2]:
#tuple concattion
t1=(1,2,3)
t2=(4,5,60)
print(t1+t2)

(1, 2, 3, 4, 5, 60)


In [5]:
#capitalize method in python
a="abhishek nisnishahad"#only starting word will be capital 
print(a.capitalize())

Abhishek nisnishahad


In [4]:
a="Abhishek nishad"
print(a.capitalize())

Abhishek nishad


In [6]:
a = "abhishek nishad"
print(a.title())


Abhishek Nishad


In [14]:
# insert the element in given list
lst = [1, 2, 3, 4]

# lst.insert(index, value)
# insert(1, 0) means:
# add 0 at index 1
# It does NOT replace any element, it only shifts elements to the right
lst.insert(1, 0)

print(lst)  # Output: [1, 0, 2, 3, 4]
lst.append(5)#add the list element at the end of the list
print(lst)
lst[0]=1
print(lst)


[1, 0, 2, 3, 4]
[1, 0, 2, 3, 4, 5]
[1, 0, 2, 3, 4, 5]


In [15]:
lst = [1, 2, 2, 3, 4, 4, 5]

# set removes duplicates but does NOT keep original order
lst = list(set(lst))
print(lst)


[1, 2, 3, 4, 5]


In [17]:
#list comprehension
list=[i for i in range(10)]
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [19]:
even_odd = lambda n: "Even" if n % 2 == 0 else "Odd"

print(even_odd(10))   # Even
print(even_odd(7))    # Odd


Even
Odd


In [21]:
even_odd=lambda n : "Even" if n % 2 == 0 else "odd"
print(even_odd(10))

Even


In [28]:
#sort and sorted method
lst=[43,35,43,354]
lst.sort()
print(lst)

lst2=[43,35,43,354]
newlst=sorted(lst2)
print(newlst)


[35, 43, 43, 354]
[35, 43, 43, 354]


In [30]:
for i in range(len(lst)):
    print(lst[i])


123
34
343
3


In [31]:
lst = [123, 34, 343, 3]

for i in xrange(len(lst)):
    print(lst[i])


NameError: name 'xrange' is not defined

In [41]:
def sum_numbers(*nums):  # use *nums for multiple positional arguments
    total = 0
    for i in nums:
        total += i  # add each number to total
    print(total)

sum_numbers(1, 2, 3)  # Output: 6


6


In [42]:
def sum_numbers(*nums):
    total=0
    for i in nums:
        total=total + i
    print(total)
sum_numbers(2,4,50)

56


In [43]:
#generators
def my_gen():
    yield 10
    yield 20
    yield 30
g=my_gen()
print(next(g))
print(next(g))

10
20


<h2>Shallow copy</h2>

In [45]:
#shallow copy not nested list
lst=[1,2,3,4]
lst2=lst.copy()
print(lst)
print(lst2)# create new seprate list ,so chnaging simple values in the copied lsit does not affect the original list,if not nested list
lst2[1]=10
print(lst)
print(lst2)

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 10, 3, 4]


In [50]:
#shallow copy with nested loop->update are reflected on both list if anyone update the list
lst=[[1,2,3,4],[5,6,7,8]]
lst2=lst.copy()
print(lst2[1][0])
lst2[1][0]=1000
print(lst)
print(lst2)
lst.append([423,343,434])#append only the lst not lst2
print(lst)
print(lst2)


5
[[1, 2, 3, 4], [1000, 6, 7, 8]]
[[1, 2, 3, 4], [1000, 6, 7, 8]]
[[1, 2, 3, 4], [1000, 6, 7, 8], [423, 343, 434]]
[[1, 2, 3, 4], [1000, 6, 7, 8]]


<h2>Deep copy</h2>

In [52]:
#deep copy without nested loop->It behave like the shallow copy 
import copy
lst1=[1,2,3,4]
lst2=copy.deepcopy(lst1)
lst2[1]=100
print(lst1)
print(lst2)

[1, 2, 3, 4]
[1, 100, 3, 4]


In [54]:
#deep copy with nested loop
lst1=[[1,2,3],[4,5,6],[7,8,9]]
lst2=copy.deepcopy(lst1)
lst2[1][0]=100#update is not reflected to the main copy
print(lst2)
print(lst1)

[[1, 2, 3], [100, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


<h3>abstract</h3>

In [56]:
from abc import ABC, abstractmethod

class Vehicle(ABC):
    def fuel(self):
        print("Fuel is needed")
    
    @abstractmethod
    def speed(self):
        pass

class Bike(Vehicle):
    def speed(self):
        print("Bike speed is 80 km/h")

obj = Bike()
obj.fuel()   # Output: Fuel is needed
obj.speed()  # Output: Bike speed is 80 km/h


Fuel is needed
Bike speed is 80 km/h


In [5]:
print(bool(""))

False


In [6]:
a=[1,2,3,4]
b=a
b.append(5)
print(a)

[1, 2, 3, 4, 5]


In [7]:
c=0.3+0.2
print(c)

0.5


In [8]:
c=0.1+0.2
print(c)

0.30000000000000004


In [16]:
print(0.1+0.1==0.2)

True


In [17]:
print(0.2+0.4==0.6)

False


In [15]:
print(0.9+0.9==1.8)

True


In [18]:
f = lambda x: x + 1
print(type(f))


<class 'function'>


<h1>Fibbonacci Series using generator</h1>

In [23]:
def fib():
    a,b=0,1
    while True:
        yield a
        a,b=b,a+b

f=fib()
print(next(f))
print(next(f))
print(next(f))
print(next(f))


0
1
1
2


In [30]:
str='The sky is blue'
trim=str.split()
print(trim)
rev=trim[::-1]
print(rev)
rev_str=' '.join(rev)
print("After reverse the sentence:",rev_str)

['The', 'sky', 'is', 'blue']
['blue', 'is', 'sky', 'The']
After reverse the sentence: blue is sky The


In [32]:
#find the charter frequncy
str='abacaagadaff'
n=len(str)-1
frequency_map={}
for i in str:
    if i not in frequency_map:
        frequency_map[i]=1
    elif i in frequency_map:
        frequency_map[i]+=1
print(frequency_map)
        


{'a': 6, 'b': 1, 'c': 1, 'g': 1, 'd': 1, 'f': 2}


In [38]:
#find the maximum and minimu
arr=[23,24,43,5,45,1,4,34]
min=arr[0]
max=arr[0]
second_min=float('inf')

for i in arr:
    if i<=min:
        second_min=min
        min=i
    elif i<second_min and i !=min:
        second_min=i
    elif i>=max:
        max=i
   
print(max,min,second_min)

45 1 4


In [42]:
#raise exception
l=[1,2,3,4]
sum=0
for i in l:
    if i==13:
        raise Exception("Exception : 1 is found")
    else:
        sum=sum+i
print(sum)

10


In [54]:
def decorator(func):
    def wrapper(a,b):
        print("sum")
        return func(a,b)
    return wrapper
@decorator
def add(a,b):
    return a+b
print(add(1,2))

sum
3
